version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${SERVER_PORT}
    command: sh -c "python -m uvicorn main:app --host=0.0.0.0 --port=${SERVER_PORT}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/app
    environment:
      - PORT=${SERVER_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
    depends_on:
      - postgres
    networks:
      - my_network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - my_network

networks:  
  my_network:
    driver: bridge

volumes:
  postgres_data:
